spring:
  data:
    cassandra: # https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cassandra/CassandraProperties.java
      keyspaceName: forum
      username: user
      password: pass
      schema-action: recreate_drop_unused # https://docs.spring.io/spring-data/cassandra/docs/current/api/org/springframework/data/cassandra/config/SchemaAction.html
logging:
  level:
    org:
      springframework:
        data:
          cassandra:
            core:
              cql: DEBUG
# api-gatewayで公開エンドポイントを絞るため、ここでは全てを許可している
management:
  endpoints:
    web:
      exposure:
        include: "*"